FROM debian:latest

RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y \
	nodejs \
	build-essential

# Run npm i in the place
RUN npm i -g supervisor
